# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polymarket.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polymarket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10polymarket.proto\x12\npolymarket\")\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0c\n\x04size\x18\x02 \x01(\x01\"\x8e\x01\n\x0bPriceChange\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0c\n\x04size\x18\x03 \x01(\x01\x12\x1e\n\x04side\x18\x04 \x01(\x0e\x32\x10.polymarket.Side\x12\x0c\n\x04hash\x18\x05 \x01(\t\x12\x10\n\x08\x62\x65st_bid\x18\x06 \x01(\x01\x12\x10\n\x08\x62\x65st_ask\x18\x07 \x01(\x01\"\xd3\x01\n\x0c\x42ookSnapshot\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x02 \x01(\t\x12\x1a\n\x12\x65xchange_timestamp\x18\x03 \x01(\x03\x12\x0c\n\x04hash\x18\x04 \x01(\t\x12$\n\x04\x62ids\x18\x05 \x03(\x0b\x32\x16.polymarket.PriceLevel\x12$\n\x04\x61sks\x18\x06 \x03(\x0b\x32\x16.polymarket.PriceLevel\x12\x11\n\ttick_size\x18\x07 \x01(\x01\x12\x18\n\x10last_trade_price\x18\x08 \x01(\x01\"h\n\nTradeEvent\x12\x0e\n\x06market\x18\x01 \x01(\t\x12\x1a\n\x12\x65xchange_timestamp\x18\x02 \x01(\x03\x12.\n\rprice_changes\x18\x03 \x03(\x0b\x32\x17.polymarket.PriceChange\"\x87\x01\n\x0bMarketEvent\x12\x1a\n\x12received_timestamp\x18\x01 \x01(\x03\x12(\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x18.polymarket.BookSnapshotH\x00\x12\'\n\x05trade\x18\x03 \x01(\x0b\x32\x16.polymarket.TradeEventH\x00\x42\t\n\x07payload*+\n\x04Side\x12\x10\n\x0cSIDE_UNKNOWN\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polymarket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIDE']._serialized_start=678
  _globals['_SIDE']._serialized_end=721
  _globals['_PRICELEVEL']._serialized_start=32
  _globals['_PRICELEVEL']._serialized_end=73
  _globals['_PRICECHANGE']._serialized_start=76
  _globals['_PRICECHANGE']._serialized_end=218
  _globals['_BOOKSNAPSHOT']._serialized_start=221
  _globals['_BOOKSNAPSHOT']._serialized_end=432
  _globals['_TRADEEVENT']._serialized_start=434
  _globals['_TRADEEVENT']._serialized_end=538
  _globals['_MARKETEVENT']._serialized_start=541
  _globals['_MARKETEVENT']._serialized_end=676
# @@protoc_insertion_point(module_scope)
